site_name: Andmekirjelduse standard
docs_dir: releases/3.0.1
site_dir: _site

theme:
  name: material
  features:
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
      toc_depth: 6

nav:
  - Avaleht: index.md
  - Legacy (vana versioon): legacy/index.md