site_name: Andmekirjelduse standard
docs_dir: docs
site_url: https://e-gov.github.io/Andmekirjelduse-Standard/

theme:
  name: material
  features:
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - toc:
      permalink: true
      toc_depth: 6

extra:
  version:
    provider: mike

nav:
  - Avaleht: index.md
  - Legacy (vana versioon): legacy/index.md